### ISSUE TITLE
Getting logged out on Refresh 

### ISSUE THREAD

**Issue by jimmytidey** [Differential/accounts-entry#144]
I'm using latest meteor with Blaze engine, and have accounts-entry as part of the differential boilerplate. 

Every time I refresh the page I'm sent back to sign in, even though my email address continues to appear top right. The route I'm using is: 

```
this.route('dashboard', {
    path: '/dashboard',
    onBeforeAction: function(){ 
        AccountsEntry.signInRequired(this);
    }
});
```

**Comment by cunneen** [comment]
@queso ,

Do you remember this change? I think Meteor has changed the conditions under which ```Meteor.loggingIn()``` returns true, and it's causing me issues.

What's happening in my scenario is that ```Meteor.loggingIn()``` is returning TRUE when the user is logged in but not connected to the server. For most apps this won't happen very often, but for my app it does.

When this happens, Iron Router complains because we're not calling this.next() at all.

Commenting out the line 36 (the test for ```unless Meteor.loggingIn()```) fixes it for me, and I can't reproduce the issue described in this ticket by refreshing the page. 
>(For others' reference, you can test it out by doing this:
>```
cd packages
git clone https://github.com/cunneen/accounts-entry.git -b feature/logging_in_check_on_signinrequired accounts-entry
meteor remove joshowens:accounts-entry
meteor add cunneen:accounts-entry
```

What should be the behaviour in this case? If the user is currently logging in, the state is somewhere between "signed in" and "not signed in". But according to the docs, Meteor.user() should be null if the user isn't signed in yet. 

Is the "if" statement I'm referring to targeted at a race condition of some sort? It seems to me that removing it makes the flow much clearer. What other options are there?

**Comment by queso** [comment]
@cunneen thanks for pinging me. I don't really work on or maintain accounts-entry anymore, just not enough time and energy in my day. I would highly suggest looking at UserAccounts stuff moving forward, @splendido has done a great job building a much better package system around this stuff.

**Comment by cunneen** [comment]
Wow, thanks for the super-speedy reply and the pointer.
